### ISSUE TITLE
Volunteer Management CRM

### ISSUE THREAD

**Issue by joegoldbeck** [techforwarren/start-here#12]
CRM to cover volunteer groups that don't have existing campaign-supported volunteer management tools

**Comment by egiurleo** [comment]
Could you give some examples of the kind of user stories this would solve? I don't have a great sense of the needs of these groups. Also, are you envisioning a web app, or maybe something cross-platform? :)

**Comment by egiurleo** [comment]
(Alternatively, would love to be connected to volunteers or coordinators experiencing these issues so I can hear about their problems first hand!)

**Comment by inbetweenbinary** [comment]
Which groups don't have access to those campaign tools?

**Comment by shaisachs** [comment]
To my understanding, local grassroots groups ("Springfield for Warren" for
ex) don't have access to the tools staff use. But some of these groups are
big enough that they need something.

Emily- I think the basic use cases are keeping track of contact
information, turning people out to events, and maybe phone banking
volunteers. Does that make sense?

**Comment by egiurleo** [comment]
@shaisachs Yes that makes total sense!

**Comment by danielnarey** [comment]
Moving conversation off of public forum until project scope and technical requirements are decided.

**Comment by joemcl** [comment]
So what's the status of this? Assuming the convo has been continued in a Slack channel.

**Comment by danielnarey** [comment]
@joemcl - This project did not move forward for various reasons. I would recommend following up with @joegoldbeck if you have related ideas.
