### ISSUE TITLE
Create icon for Tech for Warren

### ISSUE THREAD

**Issue by vyedin** [techforwarren/start-here#2]
Create an icon we can use for this github org and for community.elizabethwarren.com. Should use the EW colors:

Liberty green: #B7E4CF
red: #b61b28
blue: #232444

**Comment by danielnarey** [comment]
Besides color palette, has anyone proposed any branding guidelines or suggestions for design elements to include in a logo/icon? (for volunteer affiliates in general if not for this contingent)

Looking at designs for fundraising merch on the campaign site, I am seeing bold, sans-serif, all-caps font; thick, horizontal bars of color; different foreground/background color combos; a cool banner/marquee effect use on “Warren has a plan for that” yard sign and “PROUD” pin; one use of a photo of EW in profile on a t-shirt; and a fun “Bailey for First Dog” hankie with a silhouette of the pup.

**Comment by danielnarey** [comment]
I created two variations of a simple logo/icon design based on one of the campaign yard signs. Use it if you like it - suggestions welcome: https://github.com/danielnarey/techforwarren/tree/master/icon

**Comment by shaisachs** [comment]
Ooooh nice! How about we put it to a vote on the community site?

**Comment by joegoldbeck** [comment]
@danielnarey your icons look dope!!
