### ISSUE TITLE
Who "owns" the techforwarren repo?

### ISSUE THREAD

**Issue by Hucxley** [techforwarren/start-here#6]
We're working on the social media bots that will respond to requests for Sen. Warren's policy proposals, but we have it in a separate repo for now because I don't know who has permissions to create new repos in this org.

It wouldn't hurt to migrate it over so other people can contribute if they want, but it would be helpful to know who to coordinate with to make that happen.

Thanks, in advance, for the help/follow up!

**Comment by shaisachs** [comment]
Here you go! https://github.com/techforwarren/warrenbot

Let me know if there are any issues there.

**Comment by Hucxley** [comment]
Can you change the name to WarrenPlanBot so we know that the bot is for
Warren's plans (in case we come up with some other bots)?

**Comment by shaisachs** [comment]
:donezo:

**Comment by shaisachs** [comment]
Gonna close for now, certainly reopen if you need something else here.
